version: "3"

services:
  aircosmicdnode0:
    container_name: aircosmicdnode0
    image: "aircosmicd/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-aircosmicd.log}
    volumes:
      - ./localnet-setup/node0/aircosmicd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  aircosmicdnode1:
    container_name: aircosmicdnode1
    image: "aircosmicd/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-aircosmicd.log}
    volumes:
      - ./localnet-setup/node1/aircosmicd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  aircosmicdnode2:
    container_name: aircosmicdnode2
    image: "aircosmicd/node"
    environment:
      - ID=2
      - LOG=${LOG:-aircosmicd.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/aircosmicd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  aircosmicdnode3:
    container_name: aircosmicdnode3
    image: "aircosmicd/node"
    environment:
      - ID=3
      - LOG=${LOG:-aircosmicd.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/aircosmicd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
